/// ///////////////////////////////
// INITIAL CHANNEL CONDITIONS

module.exports = {
  'csSeed': 'USERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSER',
  'evSeed': 'USERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSER',
  'csSettlement': 'USERONE9ADDRESS9USERONE9ADDRESS9USERONE9ADDRESS9USERONE9ADDRESS9USERONE9ADDRESS9U',
  'evSettlement': 'USERTWO9ADDRESS9USERTWO9ADDRESS9USERTWO9ADDRESS9USERTWO9ADDRESS9USERTWO9ADDRESS9U',  
  'SECURITY': 2, // Security level
  'SIGNERS_COUNT': 2, // Number of parties taking signing part in the channel
  'TREE_DEPTH': 8, // Flash tree depth
  'CHANNEL_BALANCE': 2000, // Total channel Balance
  'DEPOSITS': [1000, 1000] // Users deposits
}

